version: '3.6'
services:
  # app:
    # build: .
    # volumes:
    #   - ./:/root/take_home_project
    # command: ["run-app"]
    # ports:
    #   - "8888:8888"
    # env_file:
    #   - ./local.env
  postgres:
    image: postgres:15.2
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - ./local.env
    ports:
      - 5432:5432
    restart: always

  
  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080